name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  uuid: ^3.0.0
  dartz: ^0.10.0
  http: ^0.13.4


dev_dependencies:
  build_runner: ^2.1.5
  dependencies: ^0.1.5
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
