name: pharmaplay_server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  pharma_shared_models:
    path: ../packages/pharma_shared_models
  args: ^2.0.0
  dart_jsonwebtoken: ^2.4.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  objectid: ^2.0.0
  postgres: ^2.4.3
  shelf: ^1.2.0
  shelf_router: ^1.1.2

dev_dependencies:
  build_runner: ^2.1.5
  dotenv: ^4.0.1
  email_validator: ^2.0.1
  http: ^0.13.4
  json_serializable: ^6.1.4
  lints: ^2.0.0
  mailer: ^5.0.2
  redis: ^3.1.0
  test: ^1.15.0
  test_process: ^2.0.0
  uuid: ^3.0.5
