name: pharma_shared_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

# homepage: https://www.example.com
environment:
  sdk: '>=2.16.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  equatable: ^2.0.3
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  freezed: ^1.1.1

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
