name: login_forms
description: A Flutter package to create set of pages are used for sign in/up workflow.
version: 1.0.0+2
 

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: